### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by hakanaidomu** [hakanaidomu/furima-34384#9]
最終課題であるフリマアプリの実装を行いました。
終了報告時に必要な情報については下の通りです。
最終課題の達成要件についてご確認をお願いいたします。

# 自身のフリマアプリのURL 
https://furima-34384.herokuapp.com/
# Basic認証のIDとパスワード 
ユーザー名 :admin
パスワード :1111
# 出品者用のメールアドレスとパスワード 
* メールアドレス
111@aaa
* パスワード
111aaa
# 購入者用のメールアドレスとパスワード
* メールアドレス
222@aaa
* パスワード
222aaa 

# 購入用カードの番号・期限・セキュリティコード 
* 購入用カードの番号
4242424242424242
* 期限
3 月 23 年
* セキュリティコード
123

**Comment by snkw-works** [comment]
@hakanaidomu さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像_new1](https://user-images.githubusercontent.com/54050089/107927709-b965f880-6fba-11eb-9d4a-ea77b4f917ee.png)
